### PR TITLE
Reworked README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
The original README had a link to the wiki page,
though as I now just noticed, this repository does
not have a wiki set up yet?

**Comment by wally4000** [comment]
Hey,

Thanks for that. Apologies for not merging this. 

We will be changing the way the README looks soon and would love your input on a format change.

Thanks :)

**Comment by ElectronicsArchiver** [comment]
Actually by now I have reworked the way I'm designing 
README / .. a lot, so I wouldn't want it to be merged as it~

> We will be changing the way the README looks soon and would love your input on a format change.

I'll close this PR then?

**Comment by wally4000** [comment]
Awesome. If you check the Posix Branch, i've drafted up on what we need to do, i'll do some more tinkering maybe today / tomorrow and let you know via this request (or if you're on our Discord Server will ping you).

**Comment by ElectronicsArchiver** [comment]
Sorry, I don't have Discord.

Yeah just reply here I guess,
or enable `Discussions` for
the repository~

**Comment by ElectronicsArchiver** [comment]
> i'll do some more tinkering maybe today / tomorrow

Done anything?

**Pull request closed without merging**
